[package]
name = "utilitaires"
version = "0.2.0"
edition = "2021"

[dependencies]
flume = { version = "0" }
rppal = { version = "0" }
log = "0"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "signal"] }
