name: Construction du programme lire-ejp

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 15 * *'

env:
  CARGO_TERM_COLOR: always
  CARGO_HOME:  /tmp/cache/cargo
  BRANCHE_GIT: ${{ github.head_ref || github.ref_name }}
jobs:
  construire:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Installation des dépendances requises
        run: sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - name: Rechercher si le répertoire des dépendances est en mémoire temporaire
        id: registry-cargo
        uses: actions/cache@v3
        with:
          path: ${{ env.CARGO_HOME }}
          key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}-registry-Cargo.lock
          restore-keys: |
            ${{ runner.os }}-registry-Cargo.lock
      - name: Rechercher si le répertoire de construction est en mémoire temporaire
        id: target-cargo
        uses: actions/cache@v3
        with:
          path: ./target
          key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}-target-Cargo.lock
          restore-keys: |
            ${{ runner.os }}-target-Cargo.lock
      - name: Construire l'application
        run:  |
          rustup --version
          cargo --version
          cargo build --release --example afficher_jour
      - uses: actions/upload-artifact@v3
        with:
          name: lire-ejp
          path: ./target/release/examples/afficher_jour
          retention-days: 1
          if-no-files-found: error