name: Construction de l'exemple Gestion-Ecran-Eink

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 15 * *'

env:
  CARGO_TERM_COLOR: always
  CARGO_HOME:  /tmp/cache/cargo
  BRANCHE_GIT: ${{ github.head_ref || github.ref_name }}
jobs:
  construire:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Installation des dépendances requises
        run: sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - name: Rechercher si le répertoire des dépendances est en mémoire temporaire
        id: registry-cargo
        uses: actions/cache@v3
        with:
          path: ${{ env.CARGO_HOME }}
          key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}-registry-Cargo.lock
          restore-keys: |
            ${{ runner.os }}-registry-Cargo.lock
      - name: Rechercher si le répertoire de construction est en mémoire temporaire
        id: target-cargo
        uses: actions/cache@v3
        with:
          path: ./target
          key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}-target-Cargo.lock
          restore-keys: |
            ${{ runner.os }}-target-Cargo.lock
      - name: Construire l'application
        run:  |
          rustup --version
          cargo --version
          cargo build --release --example afficher_jour
      - uses: actions/upload-artifact@v3
        with:
          name: gestion_ecran_eink_exemple
          path: ./target/release/examples/afficher_jour
          retention-days: 1
          if-no-files-found: error
  construire-armv6:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # if: github.ref == 'refs/heads/master'
    container:
      image: docker.io/rust:slim
    steps:
      - uses: actions/checkout@v3
      - name: Installation des dépendances requises
        run: | 
          dpkg --add-architecture armel && \
          apt-get update && \
          apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev -y && \
          apt-get install gcc-arm-linux-gnueabihf wget libssl-dev pkg-config make perl git -y && \
          apt-get install libcairo2-dev:armel libpango1.0-dev:armel libjpeg-dev:armel libgif-dev:armel librsvg2-dev:armel -y
      - name: Installation du compilateur armv6
        run : | 
          git clone https://github.com/abhiTronix/raspberry-pi-cross-compilers.git && \
          wget https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Raspberry%20Pi%20GCC%20Cross-Compiler%20Toolchains/Bullseye/GCC%2010.3.0/Raspberry%20Pi%201%2C%20Zero/cross-gcc-10.3.0-pi_0-1.tar.gz/download -O cross-gcc-10.3.0-pi_0-1.tar.gz && \
          tar -xf cross-gcc-10.3.0-pi_0-1.tar.gz && \
          rm cross-gcc-10.3.0-pi_0-1.tar.gz
      - name: Installateur du compilateur rust armv6
        run: rustup target add arm-unknown-linux-gnueabihf
      - name: Rechercher si le répertoire des dépendances est en mémoire temporaire
        id: registry-cargo
        uses: actions/cache@v3
        with:
          path: ${{ env.CARGO_HOME }}
          key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}-armv6-registry-Cargo.lock
          restore-keys: |
            ${{ runner.os }}-armv6-registry-Cargo.lock
      - name: Rechercher si le répertoire de construction est en mémoire temporaire
        id: target-cargo
        uses: actions/cache@v3
        with:
          path: ./target
          key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}-armv6-target-Cargo.lock
          restore-keys: |
            ${{ runner.os }}-armv6-target-Cargo.lock
      - name: Construire l'application
        run:  |
          rustup --version
          cargo --version
          cargo build --release --target arm-unknown-linux-gnueabihf --example afficher_jour
      - uses: actions/upload-artifact@v3
        with:
          name: gestion_ecran_eink_exemple_armv6
          path: ./target/release/examples/afficher_jour
          retention-days: 1
          if-no-files-found: error